// Auto-generated by scripts/update-weeks.mjs — do not edit manually.
window.HIRTENBERG_WEEKS = {
  "updatedAt": "2026-07-09T07:52:08.792Z",
  "source": "https://www.zum-hirtenberg.de/general-5",
  "weeks": [
    {
      "kw": 27,
      "year": 2026,
      "monday": "2026-06-29",
      "url": "https://www.zum-hirtenberg.de/_files/ugd/c6d06b_fc579f439e704e43b5d6eb68b7e77ea2.pdf"
    },
    {
      "kw": 28,
      "year": 2026,
      "monday": "2026-07-06",
      "url": "https://www.zum-hirtenberg.de/_files/ugd/c6d06b_247324188d8d4ae8a90374fcc6c2e607.pdf"
    },
    {
      "kw": 29,
      "year": 2026,
      "monday": "2026-07-13",
      "url": "https://www.zum-hirtenberg.de/_files/ugd/c6d06b_7ac631b4037948598977cf6066fca4d6.pdf"
    }
  ]
};
