// Auto-generated by scripts/update-weeks.mjs — do not edit manually.
window.HIRTENBERG_WEEKS = {
  "updatedAt": "2026-07-31T07:13:11.458Z",
  "source": "https://www.zum-hirtenberg.de/general-5",
  "weeks": [
    {
      "kw": 30,
      "year": 2026,
      "monday": "2026-07-20",
      "url": "https://www.zum-hirtenberg.de/_files/ugd/c6d06b_8d809025eb274ca08853d8f1a444a6a2.pdf"
    },
    {
      "kw": 31,
      "year": 2026,
      "monday": "2026-07-27",
      "url": "https://www.zum-hirtenberg.de/_files/ugd/c6d06b_0dbda57e13324d14b47a137ad8ca8f2c.pdf"
    },
    {
      "kw": 32,
      "year": 2026,
      "monday": "2026-08-03",
      "url": "https://www.zum-hirtenberg.de/_files/ugd/c6d06b_415d26276d514c8a9041d8c4c47bd0d6.pdf"
    }
  ]
};
