// Auto-generated by scripts/update-weeks.mjs — do not edit manually.
window.HIRTENBERG_WEEKS = {
  "updatedAt": "2026-07-16T06:30:40.429Z",
  "source": "https://www.zum-hirtenberg.de/general-5",
  "weeks": [
    {
      "kw": 28,
      "year": 2026,
      "monday": "2026-07-06",
      "url": "https://www.zum-hirtenberg.de/_files/ugd/c6d06b_247324188d8d4ae8a90374fcc6c2e607.pdf"
    },
    {
      "kw": 29,
      "year": 2026,
      "monday": "2026-07-13",
      "url": "https://www.zum-hirtenberg.de/_files/ugd/c6d06b_7ac631b4037948598977cf6066fca4d6.pdf"
    },
    {
      "kw": 30,
      "year": 2026,
      "monday": "2026-07-20",
      "url": "https://www.zum-hirtenberg.de/_files/ugd/c6d06b_8d809025eb274ca08853d8f1a444a6a2.pdf"
    }
  ]
};
