#!/usr/bin/env node
// Holt die Hirtenberg-Downloadseite, extrahiert KW + PDF-URL + Datumsbereich
// und schreibt weeks.js. Wird täglich von der GitHub Action ausgeführt und
// kann jederzeit manuell mit `node scripts/update-weeks.mjs` aufgerufen werden.

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const SOURCE_URL = "https://www.zum-hirtenberg.de/general-5";
const OUT_FILE = join(__dirname, "..", "weeks.js");

function mondayOfWeek(year, monthIdx, day) {
  const d = new Date(Date.UTC(year, monthIdx, day));
  const isoDayOffset = (d.getUTCDay() + 6) % 7; // Mo=0 ... So=6
  d.setUTCDate(d.getUTCDate() - isoDayOffset);
  return d.toISOString().slice(0, 10);
}

async function fetchHtml() {
  const res = await fetch(SOURCE_URL, {
    headers: {
      "User-Agent":
        "hirtenberg-order-action/1.0 (+https://github.com/DirkHeinke/hirtenberg-order)",
      Accept: "text/html,*/*",
    },
  });
  if (!res.ok) {
    throw new Error(`Quelle nicht erreichbar: HTTP ${res.status}`);
  }
  return res.text();
}

function parseWeeks(html) {
  // Im Wix-HTML steht je Block: "KW NN" ... <a href="/_files/ugd/c6d06b_<hash>.pdf"> ... DD.MM. - DD.MM.YYYY
  // Abstände <3000 Bytes (gemessen, typisch <600).
  const pattern =
    /KW\s+(\d+)[\s\S]{0,3000}?(c6d06b_[a-f0-9]+\.pdf)[\s\S]{0,1500}?(\d{2})\.(\d{2})\.\s*-\s*(\d{2})\.(\d{2})\.(\d{4})/g;
  const seen = new Set();
  const out = [];
  let m;
  while ((m = pattern.exec(html)) !== null) {
    const kw = parseInt(m[1], 10);
    const hash = m[2];
    const startDay = parseInt(m[3], 10);
    const startMonth = parseInt(m[4], 10);
    const year = parseInt(m[7], 10);
    const key = `${year}-${String(kw).padStart(2, "0")}`;
    if (seen.has(key)) continue;
    seen.add(key);
    out.push({
      kw,
      year,
      monday: mondayOfWeek(year, startMonth - 1, startDay),
      url: `https://www.zum-hirtenberg.de/_files/ugd/${hash}`,
    });
  }
  out.sort((a, b) => a.monday.localeCompare(b.monday));
  return out;
}

function buildContent(weeks) {
  const payload = {
    updatedAt: new Date().toISOString(),
    source: SOURCE_URL,
    weeks,
  };
  return (
    `// Auto-generated by scripts/update-weeks.mjs — do not edit manually.\n` +
    `window.HIRTENBERG_WEEKS = ${JSON.stringify(payload, null, 2)};\n`
  );
}

function stripTimestamp(s) {
  return s.replace(/"updatedAt":\s*"[^"]+",?\s*/g, "");
}

async function main() {
  const html = await fetchHtml();
  const weeks = parseWeeks(html);
  if (weeks.length === 0) {
    throw new Error(
      "Keine Wochen im HTML gefunden – Parser vermutlich kaputt.",
    );
  }
  const content = buildContent(weeks);

  let prev = "";
  try {
    prev = readFileSync(OUT_FILE, "utf8");
  } catch {
    /* erste Ausführung */
  }

  if (stripTimestamp(prev) === stripTimestamp(content)) {
    console.log(`Keine Änderungen (${weeks.length} Wochen).`);
    return;
  }

  writeFileSync(OUT_FILE, content);
  console.log(`${weeks.length} Wochen geschrieben nach ${OUT_FILE}.`);
  for (const w of weeks) {
    console.log(`  KW ${w.kw} (${w.monday}): ${w.url}`);
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
